project_id = "wamprxswumzvianzbhxh"

[functions.ai-chat]
verify_jwt = false

[functions.create-conversation]
verify_jwt = true

[functions.gif-search]
verify_jwt = true

[functions.translate]
verify_jwt = true

[functions.send-scheduled-messages]
verify_jwt = false

[functions.turn-credentials]
verify_jwt = false