-- Push notifications: deliver new messages and incoming calls to devices
-- even when UMS Messages is closed (Web Push).

-- Devices that opted in. One row per browser/device subscription.
CREATE TABLE public.push_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  endpoint text NOT NULL UNIQUE,
  p256dh text NOT NULL,
  auth text NOT NULL,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users see own push subscriptions" ON public.push_subscriptions
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users add own push subscriptions" ON public.push_subscriptions
  FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users update own push subscriptions" ON public.push_subscriptions
  FOR UPDATE USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users remove own push subscriptions" ON public.push_subscriptions
  FOR DELETE USING (auth.uid() = user_id);

-- VAPID key pair, generated by the send-push function on first use.
-- No policies: only the service role (edge functions) can read it.
CREATE TABLE public.push_config (
  id int PRIMARY KEY CHECK (id = 1),
  public_key text NOT NULL,
  private_key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.push_config ENABLE ROW LEVEL SECURITY;

-- Every record we have already pushed for (prevents duplicates/replays).
CREATE TABLE public.push_log (
  record_id uuid PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.push_log ENABLE ROW LEVEL SECURITY;

-- Ask the send-push function to deliver a notification for a new row.
-- Runs after the insert commits its row; any failure is swallowed so a
-- notification problem can never block sending a message or a call.
CREATE EXTENSION IF NOT EXISTS pg_net;

CREATE OR REPLACE FUNCTION public.notify_push()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  BEGIN
    PERFORM net.http_post(
      url := 'https://wamprxswumzvianzbhxh.supabase.co/functions/v1/send-push',
      headers := '{"Content-Type": "application/json"}'::jsonb,
      body := jsonb_build_object('table', TG_TABLE_NAME, 'id', NEW.id),
      timeout_milliseconds := 5000
    );
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'notify_push failed: %', SQLERRM;
  END;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS push_on_new_message ON public.messages;
CREATE TRIGGER push_on_new_message
  AFTER INSERT ON public.messages
  FOR EACH ROW EXECUTE FUNCTION public.notify_push();

DROP TRIGGER IF EXISTS push_on_new_call ON public.call_records;
CREATE TRIGGER push_on_new_call
  AFTER INSERT ON public.call_records
  FOR EACH ROW EXECUTE FUNCTION public.notify_push();
