// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded to the "earth" project (wamprxszh) so the deployed app always
// connects to this Supabase project, regardless of any host environment
// variables that might otherwise override it. These are public keys.
const SUPABASE_URL = "https://wamprxswumzvianzbhxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_pak3BE32-molooT_8ABuUQ_MqSxwpUi";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
